"""Deterministic date arithmetic for expiry clocks.

Every date in Lapse is computed here, never generated by a language model.
A model asked "when does a 180-day window opened on 2026-03-29 close?" will
answer confidently and wrongly. The model's job is to decide *which* clock
applies; this module decides *when* it closes.
"""

from __future__ import annotations

from datetime import date, timedelta

# US federal holidays that fall inside the demo window. A production build
# would use a holiday calendar library and a jurisdiction; hard-coding the
# relevant set keeps the arithmetic auditable for the dates we actually use.
_HOLIDAYS_2026 = {
    date(2026, 1, 1),    # New Year's Day
    date(2026, 1, 19),   # MLK Day
    date(2026, 2, 16),   # Presidents' Day
    date(2026, 5, 25),   # Memorial Day
    date(2026, 6, 19),   # Juneteenth
    date(2026, 7, 3),    # Independence Day (observed)
    date(2026, 9, 7),    # Labor Day
    date(2026, 11, 11),  # Veterans Day
    date(2026, 11, 26),  # Thanksgiving
    date(2026, 12, 25),  # Christmas
}


def parse_date(value: str) -> date:
    """Parse an ISO-8601 date string (YYYY-MM-DD) into a date."""
    return date.fromisoformat(value.strip())


def is_business_day(day: date) -> bool:
    """True if `day` is a weekday and not a recognised federal holiday."""
    return day.weekday() < 5 and day not in _HOLIDAYS_2026


def add_calendar_days(start: date, days: int) -> date:
    """Add calendar days. Day 0 is the trigger date itself."""
    return start + timedelta(days=days)


def add_business_days(start: date, days: int) -> date:
    """Add business days, skipping weekends and federal holidays.

    Counting begins on the first business day *after* `start`, which is the
    convention contracts use when they say "within ten business days of the
    request" -- the day of the request itself is not counted.
    """
    if days < 0:
        raise ValueError("business-day windows must be non-negative")
    current = start
    remaining = days
    while remaining > 0:
        current += timedelta(days=1)
        if is_business_day(current):
            remaining -= 1
    return current


def compute_expiry(trigger: date, window: int, business_days: bool = False) -> date:
    """Close a window of `window` days opened on `trigger`."""
    if business_days:
        return add_business_days(trigger, window)
    return add_calendar_days(trigger, window)


def days_remaining(expiry: date, today: date) -> int:
    """Whole days from `today` until `expiry`. Negative once lapsed."""
    return (expiry - today).days
