"""Deterministic date arithmetic for expiry clocks.

Every date in Lapse is computed here, never generated by a language model.
A model asked "when does a 180-day window opened on 2026-03-29 close?" will
answer confidently and wrongly. The model's job is to decide *which* clock
applies; this module decides *when* it closes.
"""

from __future__ import annotations

from datetime import date, timedelta

# US federal holidays, computed for any year rather than listed for one.
# The previous version listed 2026 only, so a ten-business-day window opened in
# late December counted New Year's Day as a working day -- a wrong deadline
# produced silently, which is the specific failure this module exists to
# prevent. A production build wants a holiday library and a jurisdiction.


def _nth_weekday(year: int, month: int, weekday: int, n: int) -> date:
    """The nth given weekday of a month (n=-1 for the last)."""
    if n > 0:
        d = date(year, month, 1)
        offset = (weekday - d.weekday()) % 7
        return d + timedelta(days=offset + 7 * (n - 1))
    nxt = date(year + (month == 12), (month % 12) + 1, 1)
    d = nxt - timedelta(days=1)
    return d - timedelta(days=(d.weekday() - weekday) % 7)


def _observed(day: date) -> date:
    """Federal holidays falling at a weekend are observed on an adjacent day."""
    if day.weekday() == 5:
        return day - timedelta(days=1)
    if day.weekday() == 6:
        return day + timedelta(days=1)
    return day


def federal_holidays(year: int) -> set[date]:
    """US federal holidays for any year, with weekend observation applied."""
    return {
        _observed(date(year, 1, 1)),                    # New Year's Day
        _nth_weekday(year, 1, 0, 3),                    # MLK Day
        _nth_weekday(year, 2, 0, 3),                    # Presidents' Day
        _nth_weekday(year, 5, 0, -1),                   # Memorial Day
        _observed(date(year, 6, 19)),                   # Juneteenth
        _observed(date(year, 7, 4)),                    # Independence Day
        _nth_weekday(year, 9, 0, 1),                    # Labor Day
        _nth_weekday(year, 10, 0, 2),                   # Columbus Day
        _observed(date(year, 11, 11)),                  # Veterans Day
        _nth_weekday(year, 11, 3, 4),                   # Thanksgiving
        _observed(date(year, 12, 25)),                  # Christmas
    }



def parse_date(value: str) -> date:
    """Parse an ISO-8601 date string (YYYY-MM-DD) into a date."""
    return date.fromisoformat(value.strip())


def is_business_day(day: date) -> bool:
    """True if `day` is a weekday and not a US federal holiday, in any year."""
    return day.weekday() < 5 and day not in federal_holidays(day.year)


def add_calendar_days(start: date, days: int) -> date:
    """Add calendar days. Day 0 is the trigger date itself.

    Rejects negative windows for the same reason the business-day variant
    does: a window cannot run backwards, and silently returning a date in the
    past would present a fabricated deadline as though it had lapsed.
    """
    if days < 0:
        raise ValueError("calendar-day windows must be non-negative")
    return start + timedelta(days=days)


def add_business_days(start: date, days: int) -> date:
    """Add business days, skipping weekends and federal holidays.

    Counting begins on the first business day *after* `start`, which is the
    convention contracts use when they say "within ten business days of the
    request" -- the day of the request itself is not counted.
    """
    if days < 0:
        raise ValueError("business-day windows must be non-negative")
    current = start
    remaining = days
    while remaining > 0:
        current += timedelta(days=1)
        if is_business_day(current):
            remaining -= 1
    return current


def compute_expiry(trigger: date, window: int, business_days: bool = False) -> date:
    """Close a window of `window` days opened on `trigger`."""
    if business_days:
        return add_business_days(trigger, window)
    return add_calendar_days(trigger, window)


def days_remaining(expiry: date, today: date) -> int:
    """Whole days from `today` until `expiry`. Negative once lapsed."""
    return (expiry - today).days
